package pcg

import bls12381 "github.com/kilic/bls12-381"

// Seed is the seed generated by the Gen function of the PCG.
// It allows to derive ECDSA tuples from the Eval function of the PCG.
type Seed struct {
	index int
	sk    *bls12381.Fr
	state uint64
}

func NewSeed() *Seed {
	return &Seed{}
}

func (s *Seed) Serialize() ([]byte, error) {
	return nil, nil
}

func (s *Seed) Deserialize(data []byte) error {
	return nil
}
